
export const UI_TEXT = {
  en: {
    title: "AI Medical Report Analyzer",
    uploadTitle: "Upload Your Medical Report",
    uploadSubtitle: "Upload an image (JPG, PNG) of your lab report for analysis.",
    uploadButton: "Choose File",
    uploading: "Uploading...",
    noFile: "No file chosen",
    analyzeButton: "Analyze Report",
    analyzing: "Analyzing...",
    patientSummary: "Simplified Summary for the Patient",
    physicianReport: "Detailed Academic Report for the Physician",
    recommendations: "Recommendations",
    generalRecs: "General",
    nutritionRecs: "Nutrition",
    physicalTherapyRecs: "Physical Therapy",
    parameter: "Parameter",
    value: "Value",
    referenceRange: "Reference Range",
    status: "Status",
    explanation: "Explanation",
    exportPDF: "Export as PDF",
    print: "Print",
    welcomeTitle: "Welcome to the AI Medical Report Analyzer",
    welcomeDesc: "Get instant, AI-powered insights from your lab reports. Simply upload a clear image of your report to begin.",
    welcomeStep1: "Upload a clear image of your medical report.",
    welcomeStep2: "Our AI analyzes the data against medical standards.",
    welcomeStep3: "Receive a detailed report for both patients and doctors.",
    loadingMessage: "Our AI is analyzing your report. This may take a moment...",
    severe: "Severe",
    moderate: "Moderate",
    normal: "Normal",
  },
  ar: {
    title: "محلل التقارير الطبية بالذكاء الاصطناعي",
    uploadTitle: "ارفع تقريرك الطبي",
    uploadSubtitle: "ارفع صورة (JPG, PNG) من تقرير المختبر للتحليل.",
    uploadButton: "اختر ملف",
    uploading: "جاري الرفع...",
    noFile: "لم يتم اختيار ملف",
    analyzeButton: "تحليل التقرير",
    analyzing: "جاري التحليل...",
    patientSummary: "ملخص مبسط للمريض",
    physicianReport: "تقرير أكاديمي مفصل للطبيب",
    recommendations: "التوصيات",
    generalRecs: "عامة",
    nutritionRecs: "التغذية",
    physicalTherapyRecs: "العلاج الطبيعي",
    parameter: "المؤشر",
    value: "القيمة",
    referenceRange: "النطاق المرجعي",
    status: "الحالة",
    explanation: "التوضيح",
    exportPDF: "تصدير كـ PDF",
    print: "طباعة",
    welcomeTitle: "أهلاً بك في محلل التقارير الطبية بالذكاء الاصطناعي",
    welcomeDesc: "احصل على رؤى فورية مدعومة بالذكاء الاصطناعي من تقارير المختبر الخاصة بك. ما عليك سوى تحميل صورة واضحة لتقريرك للبدء.",
    welcomeStep1: "ارفع صورة واضحة لتقريرك الطبي.",
    welcomeStep2: "يقوم الذكاء الاصطناعي لدينا بتحليل البيانات وفقًا للمعايير الطبية.",
    welcomeStep3: "احصل على تقرير مفصل للمرضى والأطباء.",
    loadingMessage: "يقوم الذكاء الاصطناعي بتحليل تقريرك. قد يستغرق هذا بعض الوقت...",
    severe: "شديد",
    moderate: "متوسط",
    normal: "طبيعي",
  }
};

export const STATUS_COLORS: { [key: string]: { bg: string; text: string; name: { en: string, ar: string } } } = {
  severe: { 
    bg: 'bg-red-100 dark:bg-red-900/50', 
    text: 'text-red-800 dark:text-red-200', 
    name: { en: 'Severe', ar: 'شديد' }
  },
  moderate: { 
    bg: 'bg-yellow-100 dark:bg-yellow-800/50', 
    text: 'text-yellow-800 dark:text-yellow-200', 
    name: { en: 'Moderate', ar: 'متوسط' }
  },
  normal: { 
    bg: 'bg-green-100 dark:bg-green-900/50', 
    text: 'text-green-800 dark:text-green-200',
    name: { en: 'Normal', ar: 'طبيعي' }
  },
};
